"""empty message

Revision ID: 33a2d2008df2
Revises: 
Create Date: 2021-08-23 22:53:33.867441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a2d2008df2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=120), nullable=False),
    sa.Column('rotation_period', sa.String(length=120), nullable=False),
    sa.Column('orbital_period', sa.String(length=120), nullable=False),
    sa.Column('gravity', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('surface_water', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.Column('edited', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('vehicle_class', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('length', sa.String(length=120), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=120), nullable=False),
    sa.Column('crew', sa.String(length=120), nullable=False),
    sa.Column('passengers', sa.String(length=120), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=120), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=120), nullable=False),
    sa.Column('consumables', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.Column('edited', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cargo_capacity'),
    sa.UniqueConstraint('cargo_capacity'),
    sa.UniqueConstraint('consumables'),
    sa.UniqueConstraint('consumables'),
    sa.UniqueConstraint('cost_in_credits'),
    sa.UniqueConstraint('cost_in_credits'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('crew'),
    sa.UniqueConstraint('crew'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('length'),
    sa.UniqueConstraint('length'),
    sa.UniqueConstraint('manufacturer'),
    sa.UniqueConstraint('manufacturer'),
    sa.UniqueConstraint('max_atmosphering_speed'),
    sa.UniqueConstraint('max_atmosphering_speed'),
    sa.UniqueConstraint('model'),
    sa.UniqueConstraint('model'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('passengers'),
    sa.UniqueConstraint('passengers'),
    sa.UniqueConstraint('vehicle_class'),
    sa.UniqueConstraint('vehicle_class')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=False),
    sa.Column('height', sa.String(length=250), nullable=False),
    sa.Column('homeworld_id', sa.Integer(), nullable=True),
    sa.Column('mass', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=False),
    sa.Column('created', sa.String(length=250), nullable=False),
    sa.Column('edited', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birth_year'),
    sa.UniqueConstraint('birth_year'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('eye_color'),
    sa.UniqueConstraint('eye_color'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('hair_color'),
    sa.UniqueConstraint('hair_color'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('skin_color'),
    sa.UniqueConstraint('skin_color')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('vehicles')
    op.drop_table('user')
    op.drop_table('planets')
    # ### end Alembic commands ###
