"""empty message

Revision ID: e40f3e4b05a6
Revises: cebf5845e615
Create Date: 2021-08-21 14:54:10.597648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40f3e4b05a6'
down_revision = 'cebf5845e615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=120), nullable=False),
    sa.Column('rotation_period', sa.String(length=120), nullable=False),
    sa.Column('orbital_period', sa.String(length=120), nullable=False),
    sa.Column('gravity', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('surface_water', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.Column('edited', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('diameter'),
    sa.UniqueConstraint('diameter'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('gravity'),
    sa.UniqueConstraint('gravity'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('orbital_period'),
    sa.UniqueConstraint('orbital_period'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('rotation_period'),
    sa.UniqueConstraint('rotation_period'),
    sa.UniqueConstraint('surface_water'),
    sa.UniqueConstraint('surface_water'),
    sa.UniqueConstraint('terrain'),
    sa.UniqueConstraint('terrain')
    )
    op.add_column('people', sa.Column('birth_year', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('eye_color', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('gender', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('hair_color', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('height', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('homeworld_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('mass', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('skin_color', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('created', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('edited', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'people', ['hair_color'])
    op.create_unique_constraint(None, 'people', ['eye_color'])
    op.create_unique_constraint(None, 'people', ['height'])
    op.create_unique_constraint(None, 'people', ['edited'])
    op.create_unique_constraint(None, 'people', ['birth_year'])
    op.create_unique_constraint(None, 'people', ['mass'])
    op.create_unique_constraint(None, 'people', ['created'])
    op.create_unique_constraint(None, 'people', ['skin_color'])
    op.create_unique_constraint(None, 'people', ['gender'])
    op.create_foreign_key(None, 'people', 'planet', ['homeworld_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'edited')
    op.drop_column('people', 'created')
    op.drop_column('people', 'skin_color')
    op.drop_column('people', 'mass')
    op.drop_column('people', 'homeworld_id')
    op.drop_column('people', 'height')
    op.drop_column('people', 'hair_color')
    op.drop_column('people', 'gender')
    op.drop_column('people', 'eye_color')
    op.drop_column('people', 'birth_year')
    op.drop_table('planet')
    # ### end Alembic commands ###
