"""empty message

Revision ID: e798e802d1ec
Revises: c4f4beba8b57
Create Date: 2021-08-21 15:29:55.439642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e798e802d1ec'
down_revision = 'c4f4beba8b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=120), nullable=False),
    sa.Column('rotation_period', sa.String(length=120), nullable=False),
    sa.Column('orbital_period', sa.String(length=120), nullable=False),
    sa.Column('gravity', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('terrain', sa.String(length=120), nullable=False),
    sa.Column('surface_water', sa.String(length=120), nullable=False),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.Column('edited', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('diameter'),
    sa.UniqueConstraint('diameter'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('gravity'),
    sa.UniqueConstraint('gravity'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('orbital_period'),
    sa.UniqueConstraint('orbital_period'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('rotation_period'),
    sa.UniqueConstraint('rotation_period'),
    sa.UniqueConstraint('surface_water'),
    sa.UniqueConstraint('surface_water'),
    sa.UniqueConstraint('terrain'),
    sa.UniqueConstraint('terrain')
    )
    op.drop_index('climate', table_name='planet')
    op.drop_index('climate_2', table_name='planet')
    op.drop_index('created', table_name='planet')
    op.drop_index('created_2', table_name='planet')
    op.drop_index('diameter', table_name='planet')
    op.drop_index('diameter_2', table_name='planet')
    op.drop_index('edited', table_name='planet')
    op.drop_index('edited_2', table_name='planet')
    op.drop_index('gravity', table_name='planet')
    op.drop_index('gravity_2', table_name='planet')
    op.drop_index('name', table_name='planet')
    op.drop_index('name_2', table_name='planet')
    op.drop_index('orbital_period', table_name='planet')
    op.drop_index('orbital_period_2', table_name='planet')
    op.drop_index('population', table_name='planet')
    op.drop_index('population_2', table_name='planet')
    op.drop_index('rotation_period', table_name='planet')
    op.drop_index('rotation_period_2', table_name='planet')
    op.drop_index('surface_water', table_name='planet')
    op.drop_index('surface_water_2', table_name='planet')
    op.drop_index('terrain', table_name='planet')
    op.drop_index('terrain_2', table_name='planet')
    op.drop_table('planet')
    op.drop_constraint('people_ibfk_1', 'people', type_='foreignkey')
    op.create_foreign_key(None, 'people', 'planets', ['homeworld_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_foreign_key('people_ibfk_1', 'people', 'planet', ['homeworld_id'], ['id'])
    op.create_table('planet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('diameter', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('rotation_period', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('orbital_period', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('gravity', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('population', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('climate', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('terrain', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('surface_water', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('created', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('edited', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('terrain_2', 'planet', ['terrain'], unique=False)
    op.create_index('terrain', 'planet', ['terrain'], unique=False)
    op.create_index('surface_water_2', 'planet', ['surface_water'], unique=False)
    op.create_index('surface_water', 'planet', ['surface_water'], unique=False)
    op.create_index('rotation_period_2', 'planet', ['rotation_period'], unique=False)
    op.create_index('rotation_period', 'planet', ['rotation_period'], unique=False)
    op.create_index('population_2', 'planet', ['population'], unique=False)
    op.create_index('population', 'planet', ['population'], unique=False)
    op.create_index('orbital_period_2', 'planet', ['orbital_period'], unique=False)
    op.create_index('orbital_period', 'planet', ['orbital_period'], unique=False)
    op.create_index('name_2', 'planet', ['name'], unique=False)
    op.create_index('name', 'planet', ['name'], unique=False)
    op.create_index('gravity_2', 'planet', ['gravity'], unique=False)
    op.create_index('gravity', 'planet', ['gravity'], unique=False)
    op.create_index('edited_2', 'planet', ['edited'], unique=False)
    op.create_index('edited', 'planet', ['edited'], unique=False)
    op.create_index('diameter_2', 'planet', ['diameter'], unique=False)
    op.create_index('diameter', 'planet', ['diameter'], unique=False)
    op.create_index('created_2', 'planet', ['created'], unique=False)
    op.create_index('created', 'planet', ['created'], unique=False)
    op.create_index('climate_2', 'planet', ['climate'], unique=False)
    op.create_index('climate', 'planet', ['climate'], unique=False)
    op.drop_table('planets')
    # ### end Alembic commands ###
